/*
    In this question we have to find out maximum subarray sum 
    we have to return the maximum sum generated by a subarrya or an array

    a subarray is a continous part of an array
    we have to return the sum of a subarray which maximum among all the subarrya

    Approaches:-
    first:- we can check by generating all the subarray 
    T.C = O(n^2)
    S.C = O(1)

    optimal:- we can apply kedan's algorithm here 
    it states we have to maintain a prefix sum ans where the prefix sum becomes negative make it 0
    because there no use if sum is negative and add up in it.
*/

class Solution {
public:
    int maxSubArray(vector<int>& nums) {

        int n = nums.size();

        int sum = 0;
        int max =  INT_MIN;

        for(int i =0; i<n; i++)
        {
            sum+=nums[i];

            if(sum>max)
            {
                max = sum;
            }

            if(sum<0)
            {
                sum = 0;
            }
        }

        return max;
        
    }
};
